name: Build

on: [push,pull_request,release]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
          destination: [
            'platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device'
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Clean
        run: |
          xcodebuild clean

      - name: Build
        run: |
          xcodebuild build -project Plister -scheme Plister.xcodeproj -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
        env:
          destination: ${{ matrix.destination }}



