name: Build

on: [push,pull_request,release]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
          destination: [
            'platform=iOS Simulator,OS=13.3,name=iPhone 11'
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Clean
        run: |
          xcodebuild clean

      - name: Build
        run: |
          xcodebuild build -project Plister.xcodeproj -scheme Plister -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
        env:
          destination: ${{ matrix.destination }}



