name: Plister CI

on: [push,pull_request,release]

jobs:

  SwiftBuild:
    runs-on: macOS-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@v1
      - name: Build
        run: |
          swift build -v

  SwiftTest:
    runs-on: macOS-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@v1
      - name: Run tests
        run: |
          swift test -v
        
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Clean
        run: |
          xcodebuild clean
      - name: Build
        run: |
          xcodebuild build -project Plister.xcodeproj -scheme Plister -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}

  Test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Clean
        run: |
          xcodebuild clean
      - name: Test
        run: |
          xcodebuild test -project Plister.xcodeproj -scheme Plister -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
         
  CodeCoverage:
    name: Code coverage # codecov.io
    runs-on: macOS-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Update code coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
          
          
          
#  Archive:
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout to master
#        uses: actions/checkout@master
#      - name: Archive
#        run: |
#          xcodebuild archive -project Plister.xcodeproj -scheme Plister -archivePath Plister.xcarchive
#      - name: Create ipa
#        run: |
#          xcodebuild -exportArchive -archivePath Plister.xcarchive -exportPath ipa -exportOptionsPlist ExportOptions.plist




